{!! Html::script('assets/plugins/jquery-3.1.1.js') !!}
{!! Html::script('assets/plugins/bootstrap/bootstrap.min.js') !!}
{!! Html::script('assets/plugins/metisMenu/jquery.metisMenu.js') !!}
{!! Html::script('assets/plugins/pace/pace.js') !!}
{!! Html::script('assets/scripts/siminta.js') !!}
{!! Html::script('assets/plugins/dataTables/jquery.dataTables.js') !!}
{!! Html::script('assets/plugins/dataTables/dataTables.bootstrap.js') !!}
{!! Html::script('js/all.js') !!}
{!! Html::script('assets/plugins/bootstrap/bootstrap-wysihtml5.js') !!}
{!! Html::script('assets/plugins/wysihtml5-0.3.0.js') !!}
{!! Html::script('assets/plugins/prettify.js') !!}
